version: "3"

services:
  db:
    container_name: sv-db
    image: postgres
    env_file:
      - ./.env
  server:
    container_name: sv-server
    build:
      context: .
      dockerfile: Dockerfile
    command: "python manage.py runserver 0.0.0.0:3003"
    env_file:
      - .env
    volumes:
      - ./:/app
    ports:
      - "3003:3003"
    depends_on:
      - db
