# Generated by Django 4.0.4 on 2023-03-06 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BundleItem",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50, verbose_name="name")),
                (
                    "description",
                    models.CharField(max_length=50, verbose_name="description"),
                ),
                (
                    "season",
                    models.CharField(
                        choices=[
                            ("spring", "spring"),
                            ("winter", "winter"),
                            ("summer", "summer"),
                            ("autumn", "autumn"),
                        ],
                        default="spring",
                        max_length=20,
                        verbose_name="season",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BundleRoom",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50, verbose_name="name")),
                ("reward", models.CharField(max_length=50, verbose_name="reward")),
            ],
        ),
        migrations.CreateModel(
            name="Bundle",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50, verbose_name="name")),
                ("reward", models.CharField(max_length=50, verbose_name="reward")),
                ("items", models.ManyToManyField(blank=True, to="bundles.bundleitem")),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bundles.bundleroom",
                    ),
                ),
            ],
        ),
    ]
