# Generated by Django 4.0.4 on 2023-03-06 11:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bundles", "0002_alter_bundleitem_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="bundleitem",
            name="choices",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    blank=True,
                    choices=[
                        ("spring", "spring"),
                        ("winter", "winter"),
                        ("summer", "summer"),
                        ("autumn", "autumn"),
                    ],
                    default=["spring", "summer", "autumn", "winter"],
                    max_length=10,
                    null=True,
                ),
                default=["spring"],
                size=None,
            ),
            preserve_default=False,
        ),
    ]
