# Generated by Django 4.0.4 on 2023-03-06 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bundles", "0003_bundleitem_choices"),
    ]

    operations = [
        migrations.CreateModel(
            name="Season",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50, verbose_name="name")),
            ],
        ),
        migrations.RemoveField(
            model_name="bundleitem",
            name="choices",
        ),
        migrations.RemoveField(
            model_name="bundleitem",
            name="season",
        ),
        migrations.AddField(
            model_name="bundleitem",
            name="season",
            field=models.ManyToManyField(blank=True, to="bundles.season"),
        ),
    ]
