# Generated by Django 4.0.4 on 2023-03-06 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bundles", "0006_bundleroom_bundles"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bundleroom",
            name="bundles",
        ),
        migrations.AddField(
            model_name="bundleroom",
            name="items",
            field=models.ManyToManyField(blank=True, to="bundles.bundleitem"),
        ),
    ]
