# Generated by Django 4.0.4 on 2023-03-07 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bundles", "0007_remove_bundleroom_bundles_bundleroom_items"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bundle",
            name="items",
        ),
        migrations.AddField(
            model_name="bundleitem",
            name="bundle",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="bundles.bundle",
            ),
            preserve_default=False,
        ),
    ]
