# Generated by Django 4.0.4 on 2023-03-07 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bundles", "0008_remove_bundle_items_bundleitem_bundle"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bundleroom",
            name="items",
        ),
    ]
