# Generated by Django 4.0.4 on 2023-03-07 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
        ("bundles", "0009_remove_bundleroom_items"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Season",
        ),
        migrations.AlterField(
            model_name="bundleitem",
            name="season",
            field=models.ManyToManyField(blank=True, to="common.season"),
        ),
    ]
