# Generated by Django 4.0.4 on 2023-03-09 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bundles', '0011_bundle_image_bundleitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundle',
            name='icon',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='icon'),
        ),
    ]
