# Generated by Django 4.0.4 on 2023-03-09 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bundles', '0014_reward_remove_bundle_reward_icon_alter_bundle_reward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundleroom',
            name='reward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bundles.reward'),
        ),
    ]
