# Generated by Django 4.0.4 on 2023-03-09 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bundles", "0015_alter_bundleroom_reward"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reward",
            name="icon",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="icon"
            ),
        ),
    ]
