# Generated by Django 4.0.4 on 2023-03-10 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bundles", "0016_alter_reward_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="bundle",
            name="completed_number",
            field=models.IntegerField(
                default=4, max_length=2, verbose_name="completed number"
            ),
        ),
    ]
