# Generated by Django 4.0.4 on 2023-03-10 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bundles", "0017_bundle_completed_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bundle",
            name="completed_number",
            field=models.IntegerField(default=4, verbose_name="completed number"),
        ),
    ]
